apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 2048-argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rmodi2605/Game-Portal-on-EKS-Cluster.git
    targetRevision: HEAD
    path: 2048-app
  destination:
    server: https://kubernetes.default.svc
    namespace: 2048-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
